-- Seed data removed. Products require a real user_id from auth.users.
-- To seed manually: sign up at local Supabase, copy your UUID from
-- Authentication → Users, then insert rows directly in Studio or via SQL editor.
